//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompanyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public string BlockNumber { get; set; }
        public string UBN { get; set; }
        public string BlockHash { get; set; }
        public string CreatedDate { get; set; }
        public string PreviousBlockHash { get; set; }
        public string NextBlock { get; set; }
    }
}
