//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCompanyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public string UBN { get; set; }
        public string ClaimNumber { get; set; }
        public string TheftProtection { get; set; }
        public string Description { get; set; }
        public string claimstatus { get; set; }
        public string CreationDate { get; set; }
        public string reimbursable { get; set; }
    }
}
