//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInsuranceDetail
    {
        public string UBN { get; set; }
        public string DailyPrice { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string LastDate { get; set; }
        public string StartDate { get; set; }
        public string ContractTerms { get; set; }
        public string C_contract { get; set; }
        public string theftProtection { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
